### PR TITLE
Remove email CTA from README

### PR DESCRIPTION
**Pull request by jpellizzari**
For https://github.com/weaveworks/service/issues/844

### CODE REVIEW

**Comment by rade** [comment]
We should wait until the change has landed on prod.

**Comment by jml** [comment]
@rade Can you please link to the related prod change?

**Comment by rade** [comment]
> @rade Can you please link to the related prod change?

weaveworks/service#975, which I believe got finally deployed to prod this morning.

**Comment by rade** [comment]
It looks like @davkal already pushed a commit straight to master - 3fd9ed1a39c4042365ede69354b3c221775cf04f - which addresses this. Hence the conflict. And this happened before the change had actually gone live. Grrrr.

**Pull request closed without merging**
