### PR TITLE
Move AWS storage implementations into pkg/chunk/aws

### PR DESCRIPTION
**Pull request by tomwilkie**
Move AWS-related code into chunk/aws package.

This promotes decoupling and allows us to start reusing some the more generic chunk storage tests against the other backends.

Also:
- Move to dep v0.4.1 and use prune-on-ensure behaviour.
- Update Bigtable vendoring.
- Set up test fixtures for the BigTable backend.
- Honor context cancellation in bigtable.GetChunks.
- Ensure test only asks for given chunks once per batch.
- Some renaming in the AWS pkg to remove the stutter.

### CODE REVIEW

**Comment by cboggs** [comment]
:+1: Especially on the dep upgrade - I was a hair's breadth from doing this yesterday!

At a glance, this makes chunk code far less confusing to 

It all built cleanly for me, and I rolled the querier out to our staging environment as a quick smoke-test - worked fine.

Thanks for this!

**Comment by tomwilkie** [comment]
New dep is much faster too, massive win.

Thanks!

**Comment by jml** [comment]
Couldn't get to this PR this week. @bboreham or myself will get to it next
week.

**Comment by tomwilkie** [comment]
@bboreham this has been rebase now.

**Pull request merged**
