### PR TITLE
Tweak histograms and traces

### PR DESCRIPTION
**Pull request by tomwilkie**
Adjust the histogram buckets for the query path so they're not crazy wrong, and don't trace every cache lookup, thats too many - just trace the aggregate call to the cache.

Includes #971, thats needs merging and reviewing first.

### CODE REVIEW

**Comment by gouthamve** [comment]
LGTM, based on just the last 2 commits.

**Comment by khaines** [comment]
LGTM as well, but there is a merge conflict that needs resolving first.

**Comment by cboggs** [comment]
This makes me happy, once the batch lookups are merged.

**Comment by tomwilkie** [comment]
I've moved this changes on to #981 as they depend on the code there.

**Pull request closed without merging**
