### PR TITLE
Fix log.Error -> log.Errorf

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by tomwilkie** [comment]
LGTM - would love to know why the linter didn't catch this in CI

**Comment by juliusv** [comment]
@tomwilkie I actually saw this in the `make lint` output, but apparently it isn't considered critical?

**Comment by tomwilkie** [comment]
> @tomwilkie I actually saw this in the make lint output, but apparently it isn't considered critical?

Huh - by whom?  Is that a `go lint` thing?

**Comment by juliusv** [comment]
Good question! `go tool vet` was the one that outputted this error (`./ingester/ingester_lifecycle.go:67: possible formatting directive in Error call`) and it does cause `make lint` to exit with status `2` locally, so not sure why this is not also happening in CI.

**Pull request merged**
