### PR TITLE
Only register new AM if the initial config applies

### PR DESCRIPTION
**Pull request by juliusv**
This avoids the situations where a half-initialized AM instance hangs around, but it actually panics in the web handler when the user wants to look at the UI.

### CODE REVIEW

**Comment by jml** [comment]
>  it actually panics in the web handler when the user wants to look at the UI

Why not fix this also in this PR?

**Comment by juliusv** [comment]
@jml The panic is a `nil` pointer exception because the AM's `dispatcher` is not initialized yet. Basically, the expectation of an AM instance is that it is fully initialized at least once before being used. It would seem redundant to also make the AM itself check whether it has alraedy been initialized?

**Comment by jml** [comment]
So if a user uploads a dodgy config & goes to the UI they get a 500?

**Comment by juliusv** [comment]
@jml No, they will now get "no Alertmanager for this user" (or similar) again, because their AM hasn't been initialized yet and thus not been added to the alertmanagers map. I'd expect us to handle general config errors in the AM config editing UI for now and only store a config if it looks valid.

**Pull request merged**
