### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Whoops - LGMT, but @jml has made a PR (#370) to remove this code, so I don't want to merge it as it'll conflict...

**Comment by juliusv** [comment]
Now it's just the typo fix :) Merging...

**Comment by jml** [comment]
What was it before?

**Comment by juliusv** [comment]
@jml It fixed two format string bugs, but those are now removed in #370. This one and the one below:

```go
log.Warnf("Setting original table name to %v based on path of DynamoDB URL. This will be disabled in a later release.")
```

**Comment by jml** [comment]
Thanks. I need to update my linter set up.

**Comment by tomwilkie** [comment]
There some bug in tools / ci where vet warnings aren't blocking merges.

**Pull request merged**
