### PR TITLE
Single-tenant static Alertmanager support

### PR DESCRIPTION
**Pull request by juliusv**
Part of #50

### CODE REVIEW

**Comment by juliusv** [comment]
To configure an alerting rule in a local test environment:

```bash
curl -v -XPOST --socks5-hostname localhost:8000 --globoff -H "X-Scope-OrgID: 1" 'http://configs.default.svc.cluster.local/api/configs/org/cortex' -d '{"rules_files": {"test.rules": "ALERT SomethingIsUp IF up == 1"}}'
```

**Comment by tomwilkie** [comment]
If I read this correctly, this will send alerts to all users to this alert manager?

**Comment by tomwilkie** [comment]
LGTM

**Comment by juliusv** [comment]
> If I read this correctly, this will send alerts [for] all users to this alert manager?

Yep.

**Comment by Moteesh** [comment]
Hi, 
I am trying to setup alert rules through the above mentioned method in kubernetes cluster.
i tried giving this  curl request from my cloud shell
curl -v -XPOST --socks5-hostname localhost:8000 --globoff -H "X-Scope-OrgID: 1" 'http://configs.default.svc.cluster.local/api/configs/org/cortex' -d '{"rules_files": {"test.rules": "ALERT SomethingIsUp IF up == 1"}}'

It gives the following error.
moteesh_reddy@maya-chatops:~/cortex/k8s$ curl -v -XPOST --socks5-hostname localhost:8000 --globoff -H "X-Scope-OrgID: 1" 'http://104.197.24.31:31724/api/configs/org/cortex' -d '{"rules_files": {"test.rules": "ALERT SomethingIsUp IF up == 1"}}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8000 failed: Connection refused
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network is unreachable
*   Trying ::1...
* TCP_NODELAY set
* Immediate connect fail for ::1: Network is unreachable
* Failed to connect to localhost port 8000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8000: Connection refused

Can someone tell me how to debug this and how to see if the configuration is setup properly in the configs-db

**Comment by jml** [comment]
Hi @Moteesh 

The instructions from Julius are:

 1. A little out of date
 2. Only relevant when combined with certain internal Weaveworks practices

I _think_ the problem you're seeing is due to `--socks5-hostname localhost:8000`. You don't need this if you are passing in an explicit IP address & port that's accessible from your workstation (which it looks like you're doing). 

Out of curiosity, why are you running your own Cortex instance?

jml

**Comment by Moteesh** [comment]
Hi @jml ,
I am setting up cortex for our product mayaonline.io which is a SaaS platform for containerised storage.
It is actually a management plane for openebs https://openebs.io
I was trying with a multi tenant prometheus deployment that we can do in our server and provide monitoring for the openebs volumes
I was able to setup everything else, except the rules configuration per user.
It would really help me if you provide some steps that I can follow to setup the rules through the configs service.

**Pull request merged**
