### PR TITLE
Add readiness probe

### PR DESCRIPTION
**Pull request by tomwilkie**
Add `/ready` on the ingesters which returns 200 is everyone in the ring is healthy & active, and 500 otherwise.

Will wire this up in the k8s config later.

### CODE REVIEW

**Comment by juliusv** [comment]
:+1: code-wise, though I don't know enough about how this'll be used from the K8s side (none of the ingesters are ready when there's one bad entry in the ring? I guess the plan is that any further ingester rollouts always need to wait until the whole ring becomes stable again?).

The CI tests are failing on linting.

**Comment by jml** [comment]
@juliusv Plan is that when while ingester is leaving, nothing further in the rollout can proceed until it has gracefully shut down.

I agree that this is fairly subtle (@tomwilkie and I went through it a couple of times in the office), and thus think there should be some in-code documentation about the reasoning.

**Comment by juliusv** [comment]
@jml Ok, that's what I thought at least, makes sense (for some values of "sense" :))

**Comment by tomwilkie** [comment]
> I guess the plan is that any further ingester rollouts always need to wait until the whole ring becomes stable again.

@jml it seems no comment is necessary, @juliusv worked it out from the code!

But I added some anyway.

**Comment by jml** [comment]
Thanks for the comments. Generally it's much more useful to have comments about "why" (which is harder to infer from code) than "what" or "how" (which is easier).

**Pull request merged**
