### PR TITLE
Update vendoring of Prometheus packages

### PR DESCRIPTION
**Pull request by juliusv**

### CODE REVIEW

**Comment by juliusv** [comment]
Ah, the failing `make RM= test -p` CI step is because we git-ignore any generated proto files, but the newly vendored packages need them. Will add them manually.

**Comment by tomwilkie** [comment]
> Ah, the failing make RM= test -p CI step is because we git-ignore any generated proto files, but the newly vendored packages need them. Will add them manually.

This has bit me before - can we make our gitignore more clever?

**Comment by tomwilkie** [comment]
Theres a bunch of stuff in the `vendor/github.com/prometheus/prometheus/vendor` directory - I thought we were going to delete that and only vendor what we need?

**Comment by juliusv** [comment]
> can we make our gitignore more clever?

I'll just make it ignore our specific protos.

> I thought we were going to delete that and only vendor what we need?

I tried that, but for the k8s packages I'm getting:

```
gvt fetch k8s.io/client-go/1.5/kubernetes
2017/02/13 15:09:36 Fetching: k8s.io/client-go/1.5/kubernetes
2017/02/13 15:09:41 command "fetch" failed: lstat /tmp/gvt-228264985/1.5/kubernetes: no such file or directory
```

Maybe it's because it doesn't know how to fetch code from `k8s.io`, but `gvt` doesn't allow setting a different fetch path. `gvt fetch github.com/kubernetes/client-go/1.5/kubernetes` also doesn't work because the version path component (`/1.5/`) is apparently only handled by `k8s.io` and not part of the repo. Now I can fetch `gvt fetch github.com/kubernetes/client-go/kubernetes` and rename/reshuffle everything manually, but meh?

**Comment by juliusv** [comment]
Additionally, you could argue that the versions vendored with Prometheus are the ones meant to be used together with it, though I don't think that's a big point.

**Comment by tomwilkie** [comment]
> but meh?

Indeed.  LGTM

**Pull request merged**
