### PR TITLE
Report bad samples as 400s (ingester)

### PR DESCRIPTION
**Pull request by jml**
Part of #72 

I don't really like the approach and can't see a not terrible way to do this for the distributor, so I thought I'd put it up for feedback.

### CODE REVIEW

**Comment by tomwilkie** [comment]
Its not clear to me how the new 400 errors get propagated through the distributor?  Doesn't the ingester_client.go code need to change?

**Comment by jml** [comment]
> Doesn't the ingester_client.go code need to change?

Yeah, reason I put this up is because I couldn't think of a nice way. Will just whack with a hammer until I have something that fits.

**Comment by jml** [comment]
Hammer applied. WDYT?

**Comment by tomwilkie** [comment]
LGTM

**Pull request merged**
