### PR TITLE
Distributor profiling

### PR DESCRIPTION
**Pull request by tomwilkie**
This changes to use gogoproto for unmarshalling, and adds a few more spans to see whats taking so long:

screen shot 2017-02-15 at 21 27 28

### CODE REVIEW

**Comment by tomwilkie** [comment]
[cpu.pdf](https://github.com/weaveworks/cortex/files/778470/cpu.pdf)

**Comment by tomwilkie** [comment]
After a bit more analysis, I've seen plenty of very quick unmarshalls, which leads me to believe the long tail is caused by GC.  gogoproto has some more GC friendly modes, so I'm going to try them.

**Comment by 2opremio** [comment]
@tomwilkie Can you share a raw profile I can play with? (that pdf has too many nodes :) )

**Comment by tomwilkie** [comment]
> @tomwilkie Can you share a raw profile I can play with? (that pdf has too many nodes :) )

I've lost that one, but I'll get a new one and stick it up here.

**Comment by tomwilkie** [comment]
99th %ile latency on the distributor is closer to 75ms with this change, but its still stubbornly high.  We do have some nice traces through:

screen shot 2017-02-16 at 15 13 51

Every trace I look at is different, which leads me to believe its still GC.  Going to do some 'normal' profiling now.

**Comment by tomwilkie** [comment]
Removing the label copy, latency is now ~30ms at 99th %ile:

screen shot 2017-02-16 at 17 54 28

**Comment by tomwilkie** [comment]
Reverting this change, we can see 99%-ile latency goes from 25ms->100ms.

So I'd say this fixes #289.

**Pull request merged**
