### PR TITLE
Extract function to decide if an ingester is healthy

### PR DESCRIPTION
**Pull request by bboreham**
DRY

### CODE REVIEW

**Comment by bboreham** [comment]
It turns out there's [another one](https://github.com/weaveworks/cortex/blob/master/pkg/distributor/distributor.go#L336), and this time using a different timeout.

Not sure why we would want that.  The help text for both options is exactly the same.

**Comment by bboreham** [comment]
I updated this PR.  Note that dropping `--distributor.heartbeat-timeout` will mean config has to be adjusted.

**Comment by bboreham** [comment]
Still leaves one further explicit comparison of timestamps, in `Desc.Ready()`, which is checking in the absence of a `ring.Ring` reference.  I'd need to research further to understand how that comes about.

**Comment by jml** [comment]
Recent changes LGTM.

**Pull request merged**
