### PR TITLE
Allow building and push from forks (Take II)

### PR DESCRIPTION
**Pull request by tomwilkie**

### CODE REVIEW

**Comment by tomwilkie** [comment]
@jml PTAL - thanks!

**Comment by tomwilkie** [comment]
Thanks @jml - let me know if it doesn't stick this time?

**Comment by jml** [comment]
It's all good. Sorry, I assumed that mentioning the original PR in the revert PR (#498) would notify you.

**Comment by tomwilkie** [comment]
Oh it did, I just didn't notice due to inbox grouping.  Thanks!

**Pull request merged**
