### PR TITLE
Update to Prometheus 2.3.0 code

### PR DESCRIPTION
**Pull request by bboreham**
Actually 2 commits after the 2.3.0 merge commit on master, but they look innocuous.

### CODE REVIEW

**Comment by bboreham** [comment]
The only part I've run so far is the ruler.  No change in perf observed.

**Comment by cboggs** [comment]
Happy to run this in our staging environment. We have a nice steady query load there, should be able to validate behavior easily.

**Comment by bboreham** [comment]
@cboggs good idea. It’ll most likely work fine or blow up immediately.

**Comment by cboggs** [comment]
No explosions, but no noticeable improvements either yet. Will test under a bit more significant load and see if anything shifts. :-)

**Comment by cboggs** [comment]
My ignorance of how the querier functions is going to show here, but why is the "dummy" package the only one that needed any updating? I'm assuming by the name that it's not a package that gets exercised in a "real" environment, but I'm curious now.

**Comment by bboreham** [comment]
We use and fake our various Prometheus internal interfaces, and that was the only one that changed in a noticeable way in this batch of updates.

**Comment by cboggs** [comment]
Oooh gotcha. I wanna say I've tried to do the same for some rule stuff I tried a ways back. Thanks!

Rolled this to our Prod ruler and querier, and didn't observe any noticeable impact on performance or resource utilization (positive or negative). 

No functionality broke, seems just fine. LGTM.

**Comment by bboreham** [comment]
Perf results in Weaveworks' staging environment:

Queries like `sum by(namespace) (rate(container_cpu_usage_seconds_total{namespace!=""}[2m]))"` over an hour (2,500 sample streams) go from 4 seconds to 1 second - the query engine was doing a lot of memory allocations for repeated execution of `sum`.

Other queries, not doing repeated sums, don't show any improvement at the fastest, but do show greatly reduced variability in timing, e.g. from 3-6 seconds to 3-4 seconds.

**Pull request merged**
