### PR TITLE
Retry 'Retryable' requests to dynamoDB

### PR DESCRIPTION
**Pull request by leth**
We see a number of non-fatal errors when talking to dynamodb which we could do a better job of retrying.

The AWS SDK does a good job of [flagging retryable requests](https://github.com/aws/aws-sdk-go/blob/master/aws/corehandlers/handlers.go#L177); this hooks our retry loop into that.

### CODE REVIEW

**Comment by tomwilkie** [comment]
+1 to retrying, but I would still backoff in this case; DynamoDB is very sensitive and can be overwhelmed easily.

**Comment by tomwilkie** [comment]
Probably find this also helps (if not solved) #266.

**Comment by leth** [comment]
We're seeing only occasional InternalServerErrors, most of the errors we're seeing come from https://github.com/aws/aws-sdk-go/blob/master/aws/corehandlers/handlers.go#L177 which is *before* the network request gets sent.

Also: I couldn't tell from the revision history, did you try out the built-in retrier support?

**Comment by tomwilkie** [comment]
Yes, but it made out monitor wildly inaccurate (as we were wrapping monitoring around retries etc).  Plus, out backoff scheme is better than the one in the library IIRC.  let me find a reference.

**Comment by tomwilkie** [comment]
Reference: https://www.awsarchitectureblog.com/2015/03/backoff.html

**Comment by jml** [comment]
Except the tests fail :(

**Comment by leth** [comment]
Having real troble making the current mocking tests work with with this change. Will be consulting more experts tomorrow!

**Pull request merged**
