### PR TITLE
Migrate to a protobuf encoded ring, take (2)

### LINKED ISSUE #198: Remove ingester http interface
Once the gRPC interface is in prod.

### PR DESCRIPTION
**Pull request by tomwilkie**
Original PR: #159 

By making the ring a protobuf & compressing it with snappy, I'm paving the way for increasing the number of tokens (for better load balancing - see #208) and supporting more ingesters.

Currently the ring is about 40k in JSON, and Consul's limit is 512K - so if we wanted 512 tokens per ingester, we could only have 16 ingesters with the current scheme.  This should allow many more.

Also removed the old ingester http interface - fixes #198.

### CODE REVIEW

**Comment by rade** [comment]
Context? Why are we doing this?

**Comment by tomwilkie** [comment]
After some testing, there seems to be no safe way to upgrade to this PR (as the GRPCHostname is getting lost in previous upgrades).  I'll need an intermediate PR to fix that.

**Comment by tomwilkie** [comment]
This PR: https://github.com/weaveworks/cortex/pull/219 needs to be deployed to prod before we merge this one.

**Comment by tomwilkie** [comment]
#219 is in prod, merging this now.

**Pull request merged**
